# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_log_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
