# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170930_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='status',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
