# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20170930_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
