# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20171001_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
